// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusPlanner.DAL;

#nullable disable

namespace NexusPlanner.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240408225021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusPlanner.Models.ColaboradorProyecto", b =>
                {
                    b.Property<int>("ColaboradorProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColaboradorProyectoId"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ColaboradorProyectoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ColaboradoresProyecto");

                    b.HasData(
                        new
                        {
                            ColaboradorProyectoId = 1,
                            ProyectoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            ColaboradorProyectoId = 2,
                            ProyectoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            ColaboradorProyectoId = 3,
                            ProyectoId = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            ColaboradorProyectoId = 4,
                            ProyectoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            ColaboradorProyectoId = 5,
                            ProyectoId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            ColaboradorProyectoId = 6,
                            ProyectoId = 3,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.ContadorLogin", b =>
                {
                    b.Property<string>("Mes")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Contador")
                        .HasColumnType("int");

                    b.HasKey("Mes");

                    b.ToTable("ContadorLogins");
                });

            modelBuilder.Entity("NexusPlanner.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = 1,
                            FechaCreacion = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            LoginId = 2,
                            FechaCreacion = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            LoginId = 3,
                            FechaCreacion = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            LoginId = 4,
                            FechaCreacion = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            LoginId = 5,
                            FechaCreacion = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 1
                        },
                        new
                        {
                            LoginId = 6,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 7,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 8,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 9,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 10,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 11,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 12,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 13,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 14,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 15,
                            FechaCreacion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 2
                        },
                        new
                        {
                            LoginId = 16,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 17,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 18,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 19,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 20,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 21,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 22,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 23,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 24,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 25,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 26,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 27,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 28,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 29,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 30,
                            FechaCreacion = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 3
                        },
                        new
                        {
                            LoginId = 31,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 32,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 33,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 34,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 35,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 36,
                            FechaCreacion = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 4
                        },
                        new
                        {
                            LoginId = 37,
                            FechaCreacion = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 38,
                            FechaCreacion = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 39,
                            FechaCreacion = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 40,
                            FechaCreacion = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 41,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 42,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 43,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 44,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 45,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 46,
                            FechaCreacion = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 47,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 48,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 49,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 50,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 51,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 52,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 53,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 54,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 55,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 56,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 57,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 58,
                            FechaCreacion = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 59,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 60,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 61,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 62,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 63,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 64,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 65,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 66,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 67,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 68,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 69,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 70,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 71,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 72,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 73,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 74,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 75,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 76,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 77,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 78,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 79,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 80,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 81,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 82,
                            FechaCreacion = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 83,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 84,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 85,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 86,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 87,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 88,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 89,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 90,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 91,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 92,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 93,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 94,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 95,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 96,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 97,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 98,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 99,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 100,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 101,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 102,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 103,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 104,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 105,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 106,
                            FechaCreacion = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 107,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 108,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 109,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 110,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 111,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 112,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 113,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 114,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 115,
                            FechaCreacion = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 116,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 117,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 118,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 119,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 120,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 121,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 122,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 123,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 124,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 125,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 126,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 127,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 128,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 129,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 130,
                            FechaCreacion = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 131,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 132,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 133,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 134,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 135,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 136,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 137,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 138,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 139,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 140,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 141,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 142,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 143,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 144,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        },
                        new
                        {
                            LoginId = 145,
                            FechaCreacion = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            ProyectoId = 1,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4648),
                            FechaFinal = new DateOnly(2025, 3, 3),
                            Nombre = "Proyecto de ejemplo",
                            UsuarioId = 1
                        },
                        new
                        {
                            ProyectoId = 2,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4650),
                            FechaFinal = new DateOnly(2026, 6, 6),
                            Nombre = "Proyecto de ejemplo 1",
                            UsuarioId = 2
                        },
                        new
                        {
                            ProyectoId = 3,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4652),
                            FechaFinal = new DateOnly(2027, 9, 9),
                            Nombre = "Proyecto de ejemplo 2",
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Solicitudes");

                    b.HasData(
                        new
                        {
                            SolicitudId = 1,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4772),
                            ProyectoId = 1,
                            UsuarioId = 4
                        },
                        new
                        {
                            SolicitudId = 2,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4774),
                            ProyectoId = 1,
                            UsuarioId = 5
                        },
                        new
                        {
                            SolicitudId = 3,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4775),
                            ProyectoId = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            SolicitudId = 4,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4776),
                            ProyectoId = 2,
                            UsuarioId = 5
                        },
                        new
                        {
                            SolicitudId = 5,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4777),
                            ProyectoId = 3,
                            UsuarioId = 1
                        },
                        new
                        {
                            SolicitudId = 6,
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4778),
                            ProyectoId = 3,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.Tarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFinal")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TareaId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4700),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo",
                            ProyectoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            TareaId = 2,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4702),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 1",
                            ProyectoId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            TareaId = 3,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4704),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 2",
                            ProyectoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            TareaId = 4,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4706),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 3",
                            ProyectoId = 1,
                            UsuarioId = 3
                        },
                        new
                        {
                            TareaId = 5,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4707),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 4",
                            ProyectoId = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            TareaId = 6,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4709),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 5",
                            ProyectoId = 2,
                            UsuarioId = 3
                        },
                        new
                        {
                            TareaId = 7,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4710),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 6",
                            ProyectoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            TareaId = 8,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4712),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 7",
                            ProyectoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            TareaId = 9,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4713),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 8",
                            ProyectoId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            TareaId = 10,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4717),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 9",
                            ProyectoId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            TareaId = 11,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4718),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 10",
                            ProyectoId = 3,
                            UsuarioId = 5
                        },
                        new
                        {
                            TareaId = 12,
                            Descripcion = "Esta es la descripción",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4744),
                            FechaFinal = new DateOnly(2024, 9, 10),
                            Nombre = "Tarea de ejemplo 11",
                            ProyectoId = 3,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Apellido = "Mendoza",
                            Clave = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Correo = "albert@gmail.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4392),
                            Nombre = "Albert",
                            Rol = 1,
                            Telefono = "8494736796"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Apellido = "Mendoza",
                            Clave = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Correo = "iris@gmail.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4423),
                            Nombre = "Iris",
                            Rol = 1,
                            Telefono = "8494736796"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Apellido = "Mendoza",
                            Clave = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Correo = "ronald@@gmail.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4476),
                            Nombre = "Ronald",
                            Rol = 1,
                            Telefono = "8494736796"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Apellido = "Lopez",
                            Clave = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Correo = "oly@gmail.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4500),
                            Nombre = "Oly",
                            Rol = 2,
                            Telefono = "8494736796"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Apellido = "Nicole",
                            Clave = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4",
                            Correo = "jarissa@gmail.com",
                            Estado = 1,
                            FechaCreacion = new DateTime(2024, 4, 8, 18, 50, 21, 330, DateTimeKind.Local).AddTicks(4523),
                            Nombre = "Jarissa",
                            Rol = 2,
                            Telefono = "8494736796"
                        });
                });

            modelBuilder.Entity("NexusPlanner.Models.ColaboradorProyecto", b =>
                {
                    b.HasOne("NexusPlanner.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusPlanner.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusPlanner.Models.Proyecto", b =>
                {
                    b.HasOne("NexusPlanner.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusPlanner.Models.Solicitud", b =>
                {
                    b.HasOne("NexusPlanner.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusPlanner.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NexusPlanner.Models.Tarea", b =>
                {
                    b.HasOne("NexusPlanner.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexusPlanner.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
